name: NPM Publish Protection

on:
  workflow_dispatch:
  schedule:
    # Run daily at 9 AM UTC to check if manual publishes happened
    - cron: '0 9 * * *'

jobs:
  check-npm-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Check NPM vs Git tag consistency
        run: |
          # Get current package version
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "Current package.json version: $PACKAGE_VERSION"
          
          # Check if corresponding git tag exists
          TAG_NAME="v$PACKAGE_VERSION"
          if git tag -l | grep -q "^${TAG_NAME}$"; then
            echo "✅ Git tag $TAG_NAME exists for package version $PACKAGE_VERSION"
          else
            echo "⚠️  WARNING: No git tag found for package version $PACKAGE_VERSION"
            echo "This suggests the package might have been published manually."
            echo ""
            echo "🚫 Please use release-it for all future releases:"
            echo "   • bun run release"
            echo "   • bun run release:minor" 
            echo "   • bun run release:major"
          fi
          
          # Get latest published version from NPM
          NPM_VERSION=$(npm view @heojeongbo/expo-live-activity version 2>/dev/null || echo "not-published")
          echo "Latest NPM version: $NPM_VERSION"
          
          if [ "$NPM_VERSION" != "not-published" ] && [ "$NPM_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "⚠️  Package version ($PACKAGE_VERSION) differs from NPM version ($NPM_VERSION)"
            echo "Consider running 'bun run release' if you need to publish the current version."
          fi

      - name: Remind about proper release process
        run: |
          echo ""
          echo "📋 Reminder: Always use release-it for releases!"
          echo ""
          echo "✅ Correct release process:"
          echo "1. Make your changes and commit them"
          echo "2. Run: bun run release (or release:minor/release:major)"
          echo "3. Release-it will automatically:"
          echo "   • Bump version in package.json"
          echo "   • Create commit with proper message"
          echo "   • Create Git tag"
          echo "   • Create GitHub release"
          echo "   • Publish to NPM"
          echo "   • Update CHANGELOG.md"
          echo ""
          echo "❌ Don't do manual version bumps or 'npm publish'!"